import type { Slide } from '@kit/types';

export const slides: Slide[] = [
  // --- PART 1 ---
  {
    id: 'p1-1-baseline',
    section: 1,
    sectionTitle: 'Prediction & Baseline Error',
    title: 'The Unseen Student & The Baseline Mean',
    subtitle: 'Why guessing the mean minimizes error in either direction',
    paragraphs: [
      "This unit builds up to linear regression one small step at a time, and it starts with a question that sounds almost too simple: how do you predict something when you have very little to go on? Suppose we want to guess the height of a student we have never met. We know nothing about this particular student. What we do have is a list of the heights of 100 other students who attend the same school.",
      "The sensible move is to compute the average height of those 100 students and guess that. If the average is 66 inches, we predict 66 inches. This is our first model, and it is worth pausing on what it does and does not claim. It does not claim that the unseen student is exactly 66 inches tall. Almost certainly they are not. The student might be five feet, or might be six and a half.",
      "What guessing the mean really says is something more modest: \"I have no idea how tall this student is. But if I guess the mean, I keep my error as small as I can on average, and I am equally likely to be too high as too low.\" That is what makes the mean a good baseline. It is the guess you make when you have no other information, and the point of everything that follows is to see whether extra information lets us beat it.",
      "Press 'Draw New Student' in the widget a few times. Each draw pulls a new student from the same school, and the widget shows how far off the mean-guess was. Some draws land close and some land far, but notice that the misses are not biased in one direction: the guess is too high about as often as it is too low.",
    ],
    keyTakeaways: [
      'Guessing the mean is our baseline model. Every later model will be judged by whether it beats this.',
      'A model does not promise to be exactly right. It aims to keep its errors as small as possible.',
      'The mean is the guess that is equally likely to be too high or too low, which is why it makes a fair starting point.',
    ],
    formula: {
      latex: '\\bar{y} = \\frac{1}{N} \\sum_{i=1}^{N} y_i',
      explanation: 'The sample mean (average) balances distances across all observed data points.',
      terms: [
        { symbol: '\\bar{y}', meaning: 'Sample Mean of height (inches)' },
        { symbol: 'N', meaning: 'Number of observed students (e.g. 100)' },
        { symbol: 'y_i', meaning: 'Height of the i-th individual student' },
      ],
    },
    widget: 'baseline-prediction',
  },
  {
    id: 'p1-2-spread',
    section: 1,
    sectionTitle: 'Spread & Distributions',
    title: 'Sample A vs. Sample B: Same Mean, Different Reality',
    subtitle: 'Why the mean alone fails to describe the shape of the data',
    paragraphs: [
      "The mean tells us where the middle of the data is, but it says nothing about how the data is arranged around that middle. To see why that matters for prediction, imagine two different samples of 100 students, both measured in inches.",
      "In Sample A, every single one of the 100 students is exactly 66 inches tall — five and a half feet, with no variation at all. In Sample B, 50 of the students are 60 inches tall (five feet) and the other 50 are 72 inches tall (six feet). Nobody in Sample B is anywhere near 66 inches.",
      "Now work out the mean of each. Sample A's mean is obviously 66. Sample B's mean is also 66, because 60 and 72 average to 66. So if we follow our baseline model and guess the mean, we predict 66 inches for an unseen student from either school. The predictions are identical.",
      "But our confidence in those predictions should not be identical. For Sample A, guessing 66 is guaranteed to be exactly right. For Sample B, guessing 66 is guaranteed to be wrong by six inches every single time, because no student in that school is 66 inches tall. The mean is the same, but the amount we expect to miss by is completely different.",
      "Use the widget to flip between the two samples and see the two distributions side by side. The lesson is that the mean alone is not enough to describe a dataset. We also need a way to measure its spread — how far the values tend to sit from the middle — and that is what the next few slides build.",
    ],
    keyTakeaways: [
      'Sample A and Sample B have exactly the same mean, 66 inches, so the baseline model predicts the same thing for both.',
      'Sample A has no spread at all. Sample B has a lot of spread, in two clusters far from the mean.',
      'To say how much we trust a mean-guess, we need a number that measures spread.',
    ],
    widget: 'sample-comparison',
  },
  {
    id: 'p1-3-deviations',
    section: 1,
    sectionTitle: 'Deviations & Balance',
    title: 'Deviations & The Zero-Sum Trap',
    subtitle: 'Why simple sum of deviations always cancels to zero',
    paragraphs: [
      "We want a single number that captures how spread out a sample is, so that Sample A scores low and Sample B scores high. A natural first step is to ask, for each student, how far they are from the mean. Subtract the mean from each student's height and you get a list of differences. Each difference is called a deviation. A student who is 72 inches tall in a sample with mean 66 has a deviation of +6; a student who is 60 inches tall has a deviation of −6.",
      "Now we have 100 deviations per sample, and we would like to collapse them into one number. The obvious thing to try is to add them all up. For Sample A this gives 0, which is what we want: nobody differs from the mean, so there is no spread.",
      "The trouble appears with Sample B. Half the students have a deviation of −6 and half have a deviation of +6. Fifty −6s and fifty +6s add up to exactly 0. So the sum of deviations is 0 for Sample B too, even though Sample B is clearly more spread out. As a measure of spread, the plain sum has told us nothing.",
      "This is not a coincidence of the numbers we happened to pick. The mean is defined in such a way that the deviations above it always exactly cancel the deviations below it. You can think of the mean as the balance point of the data, like the fulcrum of a seesaw: the total pull on one side is always matched by the total pull on the other. The widget shows this balance visually. Switch between the samples, or add a value of your own, and watch the mean shift so that the positive and negative deviations always sum to zero.",
      "So the sum of raw deviations is useless as a measure of spread — not because the idea of deviations is wrong, but because the signs cancel. The fix is to stop the cancellation, and the next slide does that.",
    ],
    keyTakeaways: [
      'A deviation is an observed value minus the sample mean: (yᵢ − ȳ).',
      'The sum of raw deviations is always exactly 0, because the mean is the balance point of the data.',
      'To measure total spread we need to stop positive and negative deviations from cancelling.',
    ],
    formula: {
      latex: '\\sum_{i=1}^{N} (y_i - \\bar{y}) \\equiv 0',
      explanation: 'The fundamental balancing property of the arithmetic mean in every dataset.',
      terms: [
        { symbol: 'y_i - \\bar{y}', meaning: 'Individual deviation from the mean' },
        { symbol: '\\sum', meaning: 'Summation across all N observations' },
      ],
    },
    widget: 'deviations-balance',
  },
  {
    id: 'p1-4-tss',
    section: 1,
    sectionTitle: 'Total Sum of Squares',
    title: 'Squaring Deviations & Total Sum of Squares (TSS)',
    subtitle: 'Why squaring is preferred over absolute values',
    paragraphs: [
      "The cancellation problem comes from the minus signs. There are two easy ways to get rid of them. We could take the absolute value of each deviation, turning −6 into 6, or we could square each deviation, turning −6 into 36. Either way, every deviation becomes positive, and a sum of positive numbers cannot cancel to zero.",
      "Both approaches work, but statistics almost always uses squaring, and it is worth understanding why. Squaring does more than remove the sign: it also makes big deviations count for much more than small ones. A deviation of 10 squared is 100, but a deviation of 100 squared is 10,000. The bigger miss is ten times as large, yet it contributes a hundred times as much to the total. In most settings that is considered a feature. Being wrong by a lot is usually much worse than being wrong by a little, and squaring builds that judgment into the metric.",
      "So the procedure is: take each deviation, square it, and add up all the squares. The result is called the Total Sum of Squares, abbreviated TSS. It is our first real measure of spread.",
      "Let us compute it for our two samples. In Sample A every deviation is 0, so every squared deviation is 0, and TSS is 0. In Sample B every deviation is either +6 or −6, and either way its square is 36. There are 100 students, so TSS is 36 × 100 = 3,600. Finally we have a number that separates the two samples: 0 for the sample with no spread, 3,600 for the sample with a lot of it.",
      "The widget draws each squared deviation as a literal square whose side is the deviation. TSS is the total area of all those squares, which is a useful picture to hold onto. Notice the units, too: because we squared inches, TSS is measured in square inches, which is a slightly odd unit for a measure of height. We will fix that shortly.",
    ],
    keyTakeaways: [
      'Squaring each deviation removes the sign and makes large deviations count for much more than small ones.',
      'TSS (Total Sum of Squares) = Σ(yᵢ − ȳ)², the sum of all the squared deviations.',
      'Sample A has TSS = 0 square inches; Sample B has TSS = 3,600 square inches.',
    ],
    formula: {
      latex: '\\text{TSS} = \\sum_{i=1}^{N} (y_i - \\bar{y})^2',
      explanation: 'The baseline measure of total variation in our dependent variable.',
      terms: [
        { symbol: '\\text{TSS}', meaning: 'Total Sum of Squares (in units squared)' },
        { symbol: '(y_i - \\bar{y})^2', meaning: 'Squared deviation for observation i' },
      ],
    },
    widget: 'tss-squares',
  },
  {
    id: 'p1-5-variance',
    section: 1,
    sectionTitle: 'Variance & Sample Scaling',
    title: 'The Sample Size Flaw & Variance',
    subtitle: 'Averaging the squared deviations to compare datasets of any size',
    paragraphs: [
      "TSS has one awkward property. Suppose we go back to both schools and measure twice as many students. Sample A now has 200 students who are all exactly 66 inches tall, and Sample B has 200 students, half at 60 inches and half at 72. Nothing about the shape of either sample has changed; we have simply collected more of the same.",
      "The means do not change: both are still 66. But look at what happens to TSS. Sample A's TSS is still 0, but Sample B's TSS doubles from 3,600 to 7,200, because there are now 200 squared deviations of 36 to add up instead of 100. The spread of Sample B is exactly what it was, yet the number we are using to measure spread has doubled.",
      "That is a problem if we want to compare the spread of two datasets of different sizes. A sample of 500 students would have a larger TSS than a sample of 50 even if the 50 were far more variable, simply because there are more terms in the sum. TSS measures total variation, and totals grow with sample size.",
      "The fix is the same one we use whenever a total grows with the number of items: divide by the number of items to get an average. Divide TSS by the sample size and you have the average squared deviation, which is called the variance. Variance answers the question, \"how far from the mean is a typical student, in squared units?\"",
      "Now the comparison works. Sample A has variance 0 whatever its size. Sample B with 100 students has variance 3,600 / 100 = 36, and Sample B with 200 students has variance 7,200 / 200 = 36. Same spread, same number. Use the sample-size buttons in the widget to confirm that TSS climbs as N grows while variance holds steady.",
    ],
    keyTakeaways: [
      'TSS grows whenever you add data, even if the spread has not changed, so it cannot be used to compare samples of different sizes.',
      'Variance = TSS / N is the average squared deviation. In practice we divide by (N − 1); see the note.',
      'Sample B has variance 36 whether we measure 100 students or 200.',
    ],
    note: "You will see variance computed as TSS / (N − 1) rather than TSS / N. The reason is that we are using a sample to estimate the spread of a larger population, and dividing by N tends to underestimate it slightly. Dividing by N − 1 corrects for that; it is called Bessel's correction. For a sample of 100 the difference is tiny, and the idea is the same either way: variance is the average squared deviation.",
    formula: {
      latex: 's^2 = \\frac{\\text{TSS}}{N - 1} = \\frac{1}{N - 1} \\sum_{i=1}^{N} (y_i - \\bar{y})^2',
      explanation: 'Sample Variance: Average squared deviation with Bessel\'s correction.',
      terms: [
        { symbol: 's^2', meaning: 'Sample Variance (e.g. 36 in²)' },
        { symbol: 'N - 1', meaning: 'Degrees of freedom (Bessel\'s correction for sample variance)' },
      ],
    },
    widget: 'variance-scaling',
  },
  {
    id: 'p1-6-sd',
    section: 1,
    sectionTitle: 'Standard Deviation',
    title: 'Standard Deviation: Returning to Original Units',
    subtitle: 'Taking the square root to measure average spread in inches',
    paragraphs: [
      "Variance solves the sample-size problem, but it still has the odd unit we noticed earlier. Because we squared deviations measured in inches, variance is measured in square inches. Saying that students vary from the mean by \"36 square inches\" is technically correct and completely unintuitive. Nobody thinks about height in square inches.",
      "The remedy is simple: undo the squaring. Take the square root of the variance and the units go back to inches. This quantity is called the standard deviation, and it is the measure of spread you will see most often, precisely because it lives on the same scale as the data.",
      "For Sample B, the variance is 36 square inches, and the square root of 36 is 6. So the standard deviation is 6 inches. That has a direct, plain-language meaning: students in Sample B typically sit about 6 inches away from the mean of 66. Look back at the sample and this is exactly right, since everyone is either 6 inches above or 6 inches below. For Sample A, the standard deviation is 0 inches, because nobody deviates at all.",
      "It helps to keep the chain of ideas in view. We started with deviations, which cancel. We squared them and summed to get TSS, which grows with sample size. We divided by the sample size to get variance, which is in the wrong units. We took the square root to get standard deviation, which is in the right units. Each step fixed one problem with the step before.",
      "We now have the mean, which tells us where the middle of the data is, and three related measures of spread: TSS, variance and standard deviation. Between them they describe a single variable well. The next part of the unit asks what changes when we have two variables instead of one.",
    ],
    keyTakeaways: [
      'Standard deviation = √(variance) = √(TSS / (N − 1)).',
      'Taking the square root puts spread back into the original units (inches, not square inches).',
      'In Sample B the standard deviation is 6 inches: a typical student is about 6 inches from the mean.',
    ],
    formula: {
      latex: 's = \\sqrt{s^2} = \\sqrt{\\frac{1}{N-1} \\sum_{i=1}^{N} (y_i - \\bar{y})^2}',
      explanation: 'Standard deviation puts spread back onto the original scale of measurement.',
      terms: [
        { symbol: 's', meaning: 'Sample Standard Deviation (in original units, e.g. inches)' },
        { symbol: 's^2', meaning: 'Sample Variance (squared units)' },
      ],
    },
    widget: 'standard-deviation',
  },

  // --- PART 2 ---
  {
    id: 'p2-1-shoe-height',
    section: 2,
    sectionTitle: 'Covariance & Association',
    title: 'New Information: Incorporating Shoe Size',
    subtitle: 'Moving beyond the baseline mean using auxiliary signals',
    paragraphs: [
      "Let us return to the original problem with one change. The goal is the same: predict the height of a student we have not met, using data on 100 other students from the same school. But this time we also know one more thing about the unseen student — their shoe size — and we know both the height and the shoe size of each of the 100 students in our data.",
      "In Part 1 we had no information about the unseen student, so the best we could do was guess the mean and use the standard deviation to say roughly how wrong that guess might be. Knowing the shoe size potentially changes that. Most of us have a rough sense that people with bigger feet tend to be taller, and people with smaller feet tend to be shorter. If that is true, and if we know the unseen student has size 13 feet, we should probably guess something above the mean rather than the mean itself.",
      "Notice what has happened to the shape of the problem. Instead of a single distribution of heights, we can now think about the distribution of heights among students with a given shoe size. Height is no longer something we predict in a vacuum; it is something we predict conditional on shoe size. That is the core idea behind every model in this course.",
      "Before we lean on this, though, we should check that the assumption actually holds in our data. The widget shows the 100 students as a scatter plot, with shoe size on the horizontal axis and height on the vertical axis. Look at the overall shape of the cloud. Does it drift upward as you move to the right? If so, our hunch is supported, and the next slides develop a way to measure exactly how strongly the two variables go together.",
    ],
    keyTakeaways: [
      'We now know one thing about the unseen student: their shoe size. That is our predictor variable, X.',
      'Instead of predicting height on its own, we can predict height given a particular shoe size.',
      'Before using shoe size, we need a way to measure how strongly two variables vary together.',
    ],
    widget: 'shoe-height-scatter',
  },
  {
    id: 'p2-2-quadrants',
    section: 2,
    sectionTitle: '2D Deviations & Quadrants',
    title: 'The Four Centered Quadrants',
    subtitle: 'Classifying bivariate relationships around the centroid of means',
    paragraphs: [
      "In Part 1 we computed a deviation for each student's height by subtracting the mean height. We can do exactly the same thing for shoe size: subtract the mean shoe size from each student's shoe size. Now every student has two deviations, one for height and one for shoe size, and each deviation is either positive (above average) or negative (below average).",
      "Plot the students with shoe size on the horizontal axis and height on the vertical axis, and then shift the axes so that they cross at the point where both means sit — mean shoe size and mean height. That crossing point is called the centroid, and it is the two-dimensional version of the balance point from Part 1.",
      "Drawing the axes through the centroid divides the plot into four quadrants, and every student lands in exactly one of them depending on the signs of their two deviations. A student who is taller than average with bigger-than-average feet has two positive deviations and lands in the top-right. A student who is shorter than average with smaller feet has two negative deviations and lands in the bottom-left. Taller than average with smaller feet is top-left; shorter with bigger feet is bottom-right.",
      "Here is why this is useful. If the hunch is right and taller people really do tend to have bigger feet, then most students should land in the top-right and bottom-left quadrants — the ones where both deviations have the same sign. If there were no relationship at all, students would be scattered about evenly across all four. And if the relationship were backwards, most would fall in the top-left and bottom-right.",
      "Count the points in each quadrant in the widget. The imbalance between the same-sign quadrants and the opposite-sign quadrants is the raw material for the measure of association we build on the next slide.",
    ],
    keyTakeaways: [
      'Each student now has two deviations: one for shoe size and one for height.',
      'Centering the plot at the two means (x̄, ȳ) splits it into four quadrants based on the signs of the two deviations.',
      'A positive relationship means most points sit in the two quadrants where the deviations share a sign (+/+ or −/−).',
    ],
    widget: 'four-quadrants',
  },
  {
    id: 'p2-3-covariance',
    section: 2,
    sectionTitle: 'Sum of Cross-Products',
    title: 'Cross-Products & Covariance',
    subtitle: 'Multiplying paired deviations and the strange unit problem',
    paragraphs: [
      "The quadrant picture suggests a way to turn \"most points are in the same-sign quadrants\" into a number. For each student, multiply their height deviation by their shoe-size deviation. This product is called a cross-product, and its sign tells you which kind of quadrant the student is in.",
      "Think through the four cases. A student in the top-right has two positive deviations, and positive times positive is positive. A student in the bottom-left has two negative deviations, and negative times negative is also positive. So every student in the same-sign quadrants contributes a positive cross-product. A student in the top-left or bottom-right has one positive and one negative deviation, so their cross-product is negative.",
      "Now add up all 100 cross-products. If most students are in the same-sign quadrants, the positives outweigh the negatives and the total is positive. If most are in the opposite-sign quadrants, the total is negative. If they are spread evenly, the positives and negatives roughly cancel and the total is near zero. This total is called the sum of cross-products.",
      "Just like TSS, a sum grows as we add more students, so we divide by the sample size (again using N − 1) to get an average cross-product. That average is called the covariance. Its sign tells us the direction of the relationship: positive covariance means the two variables tend to be above average together and below average together; negative covariance means one tends to be high when the other is low; covariance near zero means no consistent linear pattern.",
      "Covariance has one drawback that we need to face. Its units are the product of the two variables' units. Height is in inches and American shoe sizes are, believe it or not, measured in a unit called barleycorns, so our covariance is measured in inches × barleycorns. That is not a quantity anyone can picture, and it means covariance changes if you switch to centimetres or European shoe sizes even though the underlying relationship has not changed at all. The next slide fixes this.",
    ],
    keyTakeaways: [
      'A cross-product is one student\'s shoe-size deviation multiplied by their height deviation.',
      'Covariance is the average cross-product. Its sign gives the direction of the relationship: positive, negative or none.',
      'Covariance is measured in awkward composite units (inches × barleycorns) and changes if you change the units.',
    ],
    formula: {
      latex: '\\text{Cov}(X, Y) = \\frac{1}{N - 1} \\sum_{i=1}^{N} (x_i - \\bar{x})(y_i - \\bar{y})',
      explanation: 'Sample Covariance: The average cross-product of paired deviations.',
      terms: [
        { symbol: 'x_i - \\bar{x}', meaning: 'Shoe size deviation (in barleycorns)' },
        { symbol: 'y_i - \\bar{y}', meaning: 'Height deviation (in inches)' },
        { symbol: '\\text{Cov}', meaning: 'Covariance (units: inches × barleycorns)' },
      ],
    },
    widget: 'covariance-calc',
  },
  {
    id: 'p2-4-pearsons-r',
    section: 2,
    sectionTitle: 'Standardization to Pearson\'s r',
    title: 'Pearson\'s Correlation Coefficient (r)',
    subtitle: 'Creating a unitless metric bounded between -1 and +1',
    paragraphs: [
      "Covariance tells us the direction of a relationship, but its size is hard to interpret because it depends on the units of both variables. A covariance of 12 inches × barleycorns is not obviously large or small. We would like a version of covariance that is unitless, so that the same number means the same thing regardless of how the variables were measured.",
      "The trick is to divide by something that has the same units as covariance. We already have the standard deviation of height, which is in inches, and we can compute the standard deviation of shoe size, which is in barleycorns. Multiply those two together and the product is in inches × barleycorns — exactly the units of covariance.",
      "So divide covariance by the product of the two standard deviations. The inches cancel, the barleycorns cancel, and what remains is a pure number with no units at all. This number is Pearson's correlation coefficient, written r. Switch heights to centimetres or shoe sizes to European sizing and r does not change, because the change of units affects the numerator and the denominator in exactly the same way.",
      "Dividing by the standard deviations also has a second effect: it forces r to lie between −1 and +1. An r of +1 means every point lies exactly on an upward-sloping straight line; an r of −1 means every point lies exactly on a downward-sloping line; an r of 0 means there is no linear relationship at all. Values in between describe how tightly the cloud of points hugs a line. In practice, a correlation like 0.7 or 0.8 between shoe size and height would be considered strong.",
      "Use the noise slider in the widget to spread the points out and watch r shrink toward zero, then tighten them and watch it climb toward 1. Notice that r captures two things at once: its sign gives the direction of the relationship, and its distance from zero gives the strength.",
    ],
    keyTakeaways: [
      'r = Cov(X, Y) / (sₓ · sᵧ): covariance divided by the product of the two standard deviations.',
      'The units cancel, so r is a pure number that does not depend on how the variables were measured.',
      'r always lies between −1 and +1. Its sign gives the direction of the relationship and its size gives the strength.',
    ],
    formula: {
      latex: 'r = \\frac{\\text{Cov}(X,Y)}{s_x s_y} = \\frac{\\sum (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum (x_i - \\bar{x})^2 \\sum (y_i - \\bar{y})^2}}',
      explanation: 'Pearson\'s r: Standardized covariance, completely invariant to units of measurement.',
      terms: [
        { symbol: 'r', meaning: 'Correlation coefficient (-1 ≤ r ≤ 1)' },
        { symbol: 's_x, s_y', meaning: 'Standard deviations of X and Y' },
      ],
    },
    widget: 'pearsons-r',
  },

  // --- PART 3 ---
  {
    id: 'p3-1-lines',
    section: 3,
    sectionTitle: 'Predictions & Lines',
    title: 'From Describing Data to Making Predictions',
    subtitle: 'Drawing lines through noisy scatter clouds',
    paragraphs: [
      "We now have Pearson's r, a unitless number that tells us the direction and strength of the association between shoe size and height. That is a description of the data we have. Part 3 turns to the original goal, which was prediction: given a new student's shoe size, produce a specific guess for their height.",
      "The plan is to draw a straight line through the scatter plot and use it as a lookup. Find the new student's shoe size on the horizontal axis, go up to the line, and read off the height on the vertical axis. A line is a very simple model, but it is exactly the right one to start with, because it turns the vague idea \"bigger feet, taller person\" into a specific number for every possible shoe size.",
      "Any straight line can be described by just two numbers. The slope says how much height changes for each one-unit increase in shoe size; a slope of 2 would mean each extra shoe size goes with about 2 extra inches. The intercept says where the line crosses the vertical axis, which is the predicted height for a shoe size of zero. Together they give the familiar equation ŷ = mx + b, where the hat on ŷ is a reminder that this is a predicted height, not an observed one.",
      "The difficulty is that real data does not sit on a line. It forms a noisy cloud, and you could draw many plausible lines through it. If you took a ruler and drew one by eye, how would you know whether it was any good? How would you decide between two candidate lines that both look reasonable?",
      "Try it in the widget. Drag the slope and intercept controls to draw your own line through the students. The widget reports an error score for whatever line you draw; the next two slides explain exactly what that score is and where it comes from.",
    ],
    keyTakeaways: [
      'A prediction model takes an input (shoe size, X) and produces a predicted output (height, Ŷ).',
      'A straight line is described by two numbers: the slope m and the intercept b, giving ŷ = mx + b.',
      'Many lines could be drawn through a noisy cloud, so we need a way to score how wrong each one is.',
    ],
    widget: 'scatter-ruler',
  },
  {
    id: 'p3-2-residuals',
    section: 3,
    sectionTitle: 'Residuals & Cancellation',
    title: 'Residuals: Actual vs. Predicted (y - ŷ)',
    subtitle: 'Why the sum of residuals balances to zero for any line through the centroid',
    paragraphs: [
      "To score a line, we ask how far off its predictions are. For each student, the line predicts a height ŷ based on that student's shoe size. We also know the student's actual height y. The difference between them, actual minus predicted, is called the residual. It is the error the line makes on that one student.",
      "The sign of a residual tells you which way the line was wrong. A positive residual means the actual point sits above the line: the line predicted too low. A negative residual means the point sits below the line: the line predicted too high. A residual of zero means the line passed exactly through the point. In the widget, positive residuals are drawn as one colour and negative as another, so you can see at a glance where the line is under- and over-predicting.",
      "This should feel familiar. In Part 1, a deviation measured how far a student's height was from the mean. A residual measures how far a student's height is from the line. The line is doing the job the mean did before, except that it gives a different prediction for each shoe size instead of the same prediction for everyone.",
      "And the familiar problem comes with it. If we add up all the residuals to get a total error, the positive and negative ones cancel. Rotate the slope in the widget and watch the running total. For any line that passes through the centroid — the point at mean shoe size and mean height — the residuals sum to exactly zero, no matter how steep or shallow the line is. A wildly wrong line can have a total residual of zero.",
      "So the sum of residuals cannot tell a good line from a bad one, for exactly the reason the sum of deviations could not measure spread. And the fix is the one we already know.",
    ],
    keyTakeaways: [
      'A residual is actual minus predicted: eᵢ = yᵢ − ŷᵢ. Positive means the point is above the line, negative means below.',
      'For any line through the centroid (x̄, ȳ), the residuals sum to zero, so the plain sum cannot score a line.',
      'Just as with deviations in Part 1, we need to square the residuals before adding them up.',
    ],
    formula: {
      latex: 'e_i = y_i - \\hat{y}_i = y_i - (m x_i + b)',
      explanation: 'The individual prediction error (residual) for data point i.',
      terms: [
        { symbol: 'y_i', meaning: 'Actual observed height' },
        { symbol: '\\hat{y}_i', meaning: 'Predicted height from the model line' },
        { symbol: 'e_i', meaning: 'Residual error' },
      ],
    },
    widget: 'residuals-balance',
  },
  {
    id: 'p3-3-rss',
    section: 3,
    sectionTitle: 'Residual Sum of Squares',
    title: 'Residual Sum of Squares (RSS)',
    subtitle: 'The ultimate scoreboard for comparing candidate regression lines',
    paragraphs: [
      "We handle the cancellation the same way we did in Part 1: square each residual first, then add the squares together. Squaring makes every term positive so nothing cancels, and it makes large errors count for much more than small ones, which is usually what we want from a measure of how wrong a model is.",
      "The result is a single number called the Residual Sum of Squares, or RSS. It is the total squared error of the line across all 100 students. A line that passes close to most of the points has a small RSS; a line that misses badly has a large one. This is the error score the earlier widget was reporting when you dragged your own line around.",
      "RSS gives us a clean way to compare lines. Draw two candidate lines through the same data, compute the RSS of each, and the one with the smaller RSS is the better fit. There is no judgment call involved; it is simply the line whose predictions are closer to the actual heights overall.",
      "The widget draws each squared residual as an actual square, with the residual as its side length, sitting on the line at that point. RSS is the total area of all the squares. This is the same picture we used for TSS, and it is worth keeping in mind: TSS was the total squared distance from the mean, and RSS is the total squared distance from the line.",
      "Drag the line around in the widget and try to make the total area of the squares as small as you can. You will find you can get close but that it is hard to be sure you have found the very best line by hand. That raises the final question of the unit: out of all the lines we could possibly draw, which one has the smallest RSS, and is there a way to find it directly?",
    ],
    keyTakeaways: [
      'RSS = Σ(yᵢ − ŷᵢ)², the sum of the squared residuals. It is the total error of a line.',
      'Lower RSS means the line\'s predictions are closer to the actual data overall.',
      'The best line is the one with the smallest possible RSS. The next slide shows how to find it.',
    ],
    formula: {
      latex: '\\text{RSS} = \\sum_{i=1}^{N} (y_i - \\hat{y}_i)^2 = \\sum_{i=1}^{N} [y_i - (m x_i + b)]^2',
      explanation: 'Residual Sum of Squares (RSS): The total squared prediction error of the line.',
      terms: [
        { symbol: '\\text{RSS}', meaning: 'Residual Sum of Squares' },
        { symbol: '(y_i - \\hat{y}_i)^2', meaning: 'Squared residual for student i' },
      ],
    },
    widget: 'residual-squares',
  },
  {
    id: 'p3-4-best-fit',
    section: 3,
    sectionTitle: 'Ordinary Least Squares',
    title: 'The Line of Best Fit & Closed-Form Formula',
    subtitle: 'Connecting r, standard deviations, and the point of means',
    paragraphs: [
      "We could hunt for the best line by trial and error, adjusting the slope and intercept until RSS stops getting smaller. But there is no need. It turns out there is an exact formula for the line with the smallest possible RSS, and — this is the satisfying part — it is built entirely out of quantities we have already computed in this unit. The line it produces is called the line of best fit, and the method is called Ordinary Least Squares, or OLS, because it finds the least possible sum of squares.",
      "The slope of the best line is Pearson's r multiplied by the ratio of the two standard deviations: m = r · (s_y / s_x). Read it in two pieces. The correlation r says how strongly and in which direction the variables move together. The ratio s_y / s_x converts that into the right units, inches of height per unit of shoe size, and scales it by how spread out each variable is. If height varies a lot and shoe size varies little, each step in shoe size has to account for a lot of height, so the slope is steep.",
      "The intercept is then chosen so that the line passes through the centroid: b = ȳ − m · x̄. In words, start at the mean height, and subtract however much the slope would move you between a shoe size of zero and the mean shoe size. This guarantees the best line goes through the point of means, which is why the residuals-balance property from two slides ago always held.",
      "Put the two pieces together and you have the line ŷ = mx + b that minimizes RSS over every line that could possibly be drawn. Nothing else does better. And now the original problem is solved: take the unseen student's shoe size, plug it in as x, and the line returns a predicted height that uses everything the data can tell us about how the two variables go together.",
      "The widget walks through the four steps — r, the spread ratio, the slope, the intercept — and then lets you enter a shoe size and read off the prediction. Compare that prediction to the mean-guess from the very first slide. Whenever r is meaningfully different from zero, the line will beat the baseline, and that improvement is the whole point of regression.",
    ],
    keyTakeaways: [
      'Slope m = r · (sᵧ / sₓ): the correlation, rescaled into inches of height per unit of shoe size.',
      'Intercept b = ȳ − m · x̄: chosen so the line passes through the point of means (x̄, ȳ).',
      'This line has the smallest RSS of any line that could be drawn. That is what Ordinary Least Squares means.',
    ],
    formula: {
      latex: 'm = r \\cdot \\frac{s_y}{s_x}, \\quad b = \\bar{y} - m \\bar{x}',
      explanation: 'Closed-form formulas for the optimal regression line of best fit.',
      terms: [
        { symbol: 'm', meaning: 'Optimal slope (inches per shoe size)' },
        { symbol: 'b', meaning: 'Optimal y-intercept' },
        { symbol: 'r', meaning: 'Pearson\'s correlation coefficient' },
        { symbol: 's_y / s_x', meaning: 'Ratio of standard deviations' },
      ],
    },
    widget: 'best-fit-regression',
  },

  // --- SUMMARY / SANDBOX ---
  {
    id: 'summary-sandbox',
    section: 3,
    sectionTitle: 'Grand Interactive Sandbox & Recap',
    title: 'Statistical Mastery: Interactive Sandbox & Challenge',
    subtitle: 'Synthesize all concepts: Mean, TSS, Variance, SD, Covariance, r, RSS, and Regression',
    paragraphs: [
      "Step back and look at the whole path. We began with the simplest possible prediction, the mean, and asked how wrong it might be. Answering that led us through deviations, the squaring trick, TSS, variance and standard deviation — a set of tools for describing one variable. Adding a second variable led to cross-products, covariance and Pearson's r, tools for describing how two variables move together. And finally, wanting a prediction rather than a description led to lines, residuals, RSS and the least-squares formula that finds the best line.",
      "Notice how often the same idea came back. Deviations cancelled, so we squared them; residuals cancelled, so we squared them too. TSS grew with sample size, so we averaged it; the sum of cross-products grew with sample size, so we averaged that too. Covariance had messy units, so we divided by standard deviations to cancel them. Once you see these moves, most of the rest of the course is variations on them.",
      "The sandbox below puts all of it in one place. Generate your own dataset, adjust the noise and the sample size, and watch every statistic in the chain update live: the means, TSS, variance, standard deviation, covariance, r, the fitted slope and intercept, and RSS. Then try the recap challenge to check how well the ideas have stuck.",
    ],
    keyTakeaways: [
      'Baseline model: with no other information, guessing the mean ȳ keeps squared error as small as possible.',
      'Spread of one variable: TSS grows with N; variance divides by N − 1; standard deviation takes the square root to restore the original units.',
      'Association of two variables: covariance gives the direction in composite units; Pearson\'s r standardizes it to the range −1 to +1.',
      'Linear model: OLS finds the line ŷ = mx + b with the smallest RSS, using m = r (sᵧ / sₓ) and b = ȳ − m x̄.',
    ],
    widget: 'grand-sandbox',
  },
];
